### ISSUE TITLE
'I have an accelerator for you.' - doesn't show up

### ISSUE THREAD

**Issue by oppZ** [DoicRM/Cyberpunk-Text-Game#1]
So there is a point of time where I collected the accelerator and the possibilities that come up are : 
        [1] 'What do you have?'
        [2] 'How's business going?'
        [3] 'I have an accelerator for you.'
        [4] 'I have to go...'

When I press 3, it says that I have selected "I have to go..."

**Comment by DoicRM** [comment]
I've only added a dialogue option for now, but I'll try to include a function as soon as possible
